<?php

use App\Models\Brand;
use App\Models\Category;
use App\Models\Guide;
use App\Models\Listing;
use App\Models\ListingMedia;
use App\Models\Role;
use App\Models\SellerProfile;
use App\Models\SeoRedirect;
use App\Models\User;
use App\Services\SeoRedirectService;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;

test('only published guides are public and included in their dedicated sitemap', function () {
    $category = Category::factory()->create(['name' => 'Blenders']);
    $listing = Listing::factory()->for($category)->create();
    ListingMedia::factory()->for($listing)->create();
    $published = Guide::factory()->published()->create([
        'title' => 'Safe <script>alert(1)</script> Blender Guide',
        'slug' => 'safe-blender-guide',
        'sections' => [['heading' => 'Choose safely', 'paragraphs' => ['Never render <script>alert(2)</script> as HTML.']]],
    ]);
    $published->categories()->attach($category, ['sort_order' => 0]);
    $draft = Guide::factory()->create(['slug' => 'private-draft-guide']);
    $future = Guide::factory()->create(['slug' => 'future-guide', 'status' => 'published', 'published_at' => now()->addDay()]);

    $response = $this->get(route('guides.show', $published->slug));

    $response->assertOk()
        ->assertDontSee('<script>alert(2)</script>', false)
        ->assertSee('"@type":"Article"', false)
        ->assertSee('prodeals-social-card.png', false)
        ->assertSee('"@type":"BreadcrumbList"', false)
        ->assertSee('name="robots" content="index,follow,max-image-preview:large"', false)
        ->assertInertia(fn ($page) => $page
            ->where('guide.title', $published->title)
            ->where('guide.sections.0.paragraphs.0', 'Never render <script>alert(2)</script> as HTML.')
            ->where('guide.categories.0.slug', $category->slug)
            ->where('relatedListings.0.slug', $listing->slug));

    $this->get(route('guides.show', $draft->slug))->assertNotFound();
    $this->get(route('guides.show', $future->slug))->assertNotFound();

    $this->get(route('sitemap.index'))
        ->assertOk()
        ->assertSee(route('sitemap.guides'), false);
    $this->get(route('sitemap.guides'))
        ->assertOk()
        ->assertSee(route('guides.show', $published->slug), false)
        ->assertDontSee($draft->slug, false)
        ->assertDontSee($future->slug, false);
});

test('guide category and product links are bidirectional and crawlable', function () {
    $category = Category::factory()->create(['seo_intro' => "First safe paragraph.\n\nSecond safe paragraph."]);
    $brand = Brand::factory()->create();
    $listing = Listing::factory()->for($category)->for($brand)->create();
    $guide = Guide::factory()->published()->create();
    $guide->categories()->attach($category, ['sort_order' => 0]);

    $this->get(route('categories.show', $category->slug))
        ->assertOk()
        ->assertInertia(fn ($page) => $page
            ->where('intro', "First safe paragraph.\n\nSecond safe paragraph.")
            ->where('relatedGuides.0.slug', (string) $guide->slug));

    $this->get(route('listings.show', $listing->slug))
        ->assertOk()
        ->assertInertia(fn ($page) => $page->where('relatedGuides.0.slug', (string) $guide->slug));

    $this->get(route('brands.show', $brand->slug))
        ->assertOk()
        ->assertInertia(fn ($page) => $page->where('relatedGuides.0.slug', (string) $guide->slug));
});

test('guide hero URLs are generated by the configured R2 media disk', function () {
    config([
        'filesystems.media' => 'r2',
        'filesystems.disks.r2.url' => 'https://media.prodeals.test',
    ]);
    $guide = Guide::factory()->published()->create([
        'hero_image_disk' => 'r2',
        'hero_image_path' => 'guides/hero.webp',
        'hero_image_alt' => 'A product comparison',
    ]);

    expect($guide->heroImageUrl())->toBe('https://media.prodeals.test/guides/hero.webp');
});

test('exact fallback redirects record hits and chains collapse to a terminal path', function () {
    $service = app(SeoRedirectService::class);
    $service->create(['source_path' => '/new-shop', 'destination_path' => '/listings', 'is_active' => true]);
    $service->create(['source_path' => '/old-shop/', 'destination_path' => '/new-shop', 'is_active' => true]);

    expect(SeoRedirect::query()->where('source_path', '/old-shop')->value('destination_path'))->toBe('/listings');

    $this->get('/old-shop')->assertRedirect('/listings')->assertStatus(301);
    $this->get('/old-shop/extra')->assertNotFound();

    $redirect = SeoRedirect::query()->where('source_path', '/old-shop')->firstOrFail();
    expect($redirect->fresh()->hit_count)->toBe(1)
        ->and($redirect->fresh()->last_hit_at)->not->toBeNull();
});

test('self redirects and redirect loops are rejected', function () {
    $service = app(SeoRedirectService::class);

    expect(fn () => $service->create(['source_path' => '/same', 'destination_path' => '/same/', 'is_active' => true]))
        ->toThrow(ValidationException::class);

    $service->create(['source_path' => '/a', 'destination_path' => '/b', 'is_active' => true]);

    expect(fn () => $service->create(['source_path' => '/b', 'destination_path' => '/a', 'is_active' => true]))
        ->toThrow(ValidationException::class);
});

test('administrators manage legacy redirects and super administrators restore archived records', function () {
    $admin = User::factory()->create();
    $adminRole = Role::factory()->create(['name' => 'admin']);
    $admin->roles()->attach($adminRole);

    $this->actingAs($admin)->post(route('admin.seo-redirects.store'), [
        'source_path' => '/legacy-sale',
        'destination_path' => '/listings',
        'is_active' => true,
    ])->assertRedirect(route('admin.seo-redirects.index'));

    $redirect = SeoRedirect::query()->where('source_path', '/legacy-sale')->firstOrFail();
    $this->actingAs($admin)->patch(route('admin.seo-redirects.update', $redirect), [
        'source_path' => '/legacy-sale',
        'destination_path' => '/guides',
        'is_active' => true,
    ])->assertRedirect(route('admin.seo-redirects.index'));
    $this->get('/legacy-sale')->assertRedirect('/guides')->assertStatus(301);

    $this->actingAs($admin)->delete(route('admin.seo-redirects.destroy', $redirect))->assertRedirect(route('admin.seo-redirects.index'));
    expect($redirect->fresh()->trashed())->toBeTrue();
    $this->actingAs($admin)->post(route('admin.seo-redirects.restore', $redirect->id))->assertForbidden();

    $superAdminRole = Role::factory()->create(['name' => 'super_admin']);
    $admin->roles()->attach($superAdminRole);
    $admin->unsetRelation('roles');
    $this->actingAs($admin)->post(route('admin.seo-redirects.restore', $redirect->id))->assertRedirect(route('admin.seo-redirects.index'));
    expect($redirect->fresh()->trashed())->toBeFalse();

    $this->actingAs($admin)->post(route('admin.seo-redirects.store'), [
        'source_path' => '/legacy-sale/',
        'destination_path' => '/listings',
        'is_active' => true,
    ])->assertSessionHasErrors('source_path');

    $this->actingAs($admin)->post(route('admin.seo-redirects.store'), [
        'source_path' => '/unsafe-external',
        'destination_path' => 'https://example.com',
        'is_active' => true,
    ])->assertSessionHasErrors('destination_path');
});

test('discovery responses use shared caching while the merchant feed remains live', function () {
    $sitemap = $this->get(route('sitemap.index'));
    $robots = $this->get(route('robots'));
    $merchant = $this->get(route('feeds.google_merchant'));

    foreach ([$sitemap, $robots] as $response) {
        $response->assertOk();
        expect($response->headers->get('Cache-Control'))
            ->toContain('public', 'max-age=300', 's-maxage=3600', 'stale-while-revalidate=86400');
        expect($response->headers->get('ETag'))->not->toBeNull();
    }

    expect($merchant->headers->get('Cache-Control'))->toContain('no-cache');
});

test('robots output has exactly one sitemap declaration and the intended crawler rules', function () {
    $body = $this->get(route('robots'))->assertOk()->getContent();

    expect(substr_count($body, 'Sitemap: '.route('sitemap.index')))->toBe(1)
        ->and($body)->toContain("User-agent: Google-Extended\nDisallow: /")
        ->and($body)->toContain("User-agent: OAI-SearchBot\nAllow: /")
        ->and($body)->toContain("User-agent: *\nAllow: /");
});

test('admins publish validated structured guides with hero media on R2', function () {
    Storage::fake('r2');
    config(['filesystems.media' => 'r2']);
    $admin = User::factory()->create();
    $role = Role::factory()->create(['name' => 'admin']);
    $admin->roles()->attach($role);
    $category = Category::factory()->create();

    $payload = [
        'title' => 'Choosing a safe charger',
        'slug' => 'choosing-a-safe-charger',
        'excerpt' => 'A concise charger buying guide for Sri Lankan shoppers.',
        'quick_answer' => 'Match the connector, wattage and supported charging protocol.',
        'sections' => [['heading' => 'Check compatibility', 'paragraphs' => ['Match both ends of the cable and the charging protocol.']]],
        'buying_checklist' => ['Confirm connector and wattage.'],
        'hero_image' => UploadedFile::fake()->image('charger.jpg', 1600, 900),
        'hero_image_alt' => 'Phone charger and cable comparison',
        'seo_title' => 'Choosing a Safe Phone Charger - ProDeals.lk',
        'seo_description' => 'Compare connector, wattage and fast-charging compatibility before buying a phone charger in Sri Lanka.',
        'primary_query' => 'phone charger types',
        'supporting_queries' => ['usb c charger sri lanka'],
        'trends_researched_at' => today()->toDateString(),
        'status' => 'published',
        'category_ids' => [$category->id],
    ];

    $this->actingAs($admin)->post(route('admin.guides.store'), $payload)->assertRedirect();

    $guide = Guide::query()->where('slug', 'choosing-a-safe-charger')->firstOrFail();
    expect($guide->hero_image_disk)->toBe('r2')
        ->and($guide->isPublished())->toBeTrue()
        ->and($guide->categories->first()->id)->toBe($category->id);
    Storage::disk('r2')->assertExists($guide->hero_image_path);
    $this->get(route('guides.show', $guide->slug))->assertOk();

    unset($payload['hero_image']);
    $payload['slug'] = 'choosing-a-safe-phone-charger';
    $this->actingAs($admin)->patch(route('admin.guides.update', $guide), $payload)->assertRedirect();
    $guide->refresh();
    $this->get('/guides/choosing-a-safe-charger?utm_source=legacy')
        ->assertRedirect('/guides/choosing-a-safe-phone-charger?utm_source=legacy')
        ->assertStatus(301);

    $this->actingAs($admin)->delete(route('admin.guides.destroy', $guide))->assertRedirect(route('admin.guides.index'));
    expect($guide->fresh()->trashed())->toBeTrue();

    $superAdminRole = Role::factory()->create(['name' => 'super_admin']);
    $admin->roles()->attach($superAdminRole);
    $this->actingAs($admin)->post(route('admin.guides.restore', $guide->id))->assertRedirect(route('admin.guides.index'));
    expect($guide->fresh()->trashed())->toBeFalse();
});

test('initial trends content seed is idempotent and preserves existing editorial copy', function () {
    foreach (['Food Mixers & Blenders', 'Rice Cookers', 'Electric Kettles', 'Power Adapters & Chargers', 'Storage & Data Transfer Cables'] as $name) {
        Category::factory()->create(['name' => $name]);
    }
    $blenders = Category::query()->where('name', 'Food Mixers & Blenders')->firstOrFail();
    $blenders->update(['seo_title' => 'Existing editor title']);
    $seller = SellerProfile::factory()->create(['status' => 'approved', 'about' => null]);
    Listing::factory()->for($seller)->for($blenders)->create();

    $this->artisan('seo:seed-growth-content')->assertSuccessful();
    $this->artisan('seo:seed-growth-content')->assertSuccessful();

    expect(Guide::query()->count())->toBe(5)
        ->and(Guide::query()->where('status', 'published')->count())->toBe(5)
        ->and(SeoRedirect::query()->where('source_path', '/shop')->where('destination_path', '/listings')->count())->toBe(1)
        ->and($blenders->fresh()->seo_title)->toBe('Existing editor title')
        ->and($blenders->fresh()->seo_focus_query)->toBe('blender price in sri lanka')
        ->and($blenders->fresh()->seo_intro)->toContain("\n\n")
        ->and($blenders->fresh()->seo_intro)->not->toContain('\n')
        ->and($seller->fresh()->about)->toContain('Browse products currently available');

    $archivedGuide = Guide::query()->firstOrFail();
    $archivedGuide->delete();
    $this->artisan('seo:seed-growth-content')->assertSuccessful();
    expect(Guide::withTrashed()->count())->toBe(5)
        ->and($archivedGuide->fresh()->trashed())->toBeTrue();
});
