[program:prodeals-worker]
command=/usr/bin/php8.4 /var/www/prodeals/current/artisan queue:work database --sleep=3 --tries=3 --timeout=75 --max-time=3600
directory=/var/www/prodeals/current
user=deploy
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=85
redirect_stderr=true
stdout_logfile=/var/www/prodeals/shared/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=APP_ENV="production"
